name: Build & Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allows manual execution from the GitHub UI

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout
      packages: write # Required to push images to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Using v4 for latest features and security

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Recommended for advanced build capabilities

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/caddyl4-cloudflare-docker-proxy
          tags: |
            type=raw,value=latest,enable={{is_default_branch}} # Tag 'latest' only on the default branch (main)
            type=sha # Tag with the short commit SHA

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # You can specify a Dockerfile if it's not named 'Dockerfile' in the root:
          # file: ./path/to/Dockerfile
